# Site settings
title: James Baierski
description: Personal website and portfolio
url: "https://jamesbaierski.github.io"
baseurl: ""

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown

# Basic plugins for SEO and feeds
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - projects.md

# Social links
github_username: # your GitHub username
linkedin_username: # your LinkedIn username

# Include README in build
include:
  - README.md

# Exclude development-related files
exclude:
  - Gemfile
  - Gemfile.lock
