# _config.yml
title: James Baierski
description: Personal Portfolio & Blog
baseurl: ""
url: ""
github_username: jbaierski
linkedin_username: jamesbaierski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - about.md
  - blog.md
  - projects.md
  - contact.md

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "James Baierski"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Custom settings
show_excerpts: true
date_format: "%B %-d, %Y"

# File: _layouts/default.html
---
layout: default
---
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page.title }} | {{ site.title }}</title>
    <link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">
</head>
<body>
    <header>
        <nav>
            <a href="{{ '/' | relative_url }}" class="site-title">{{ site.title }}</a>
            <div class="nav-links">
                {% for page in site.header_pages %}
                    <a href="{{ page.url | relative_url }}">{{ page.title }}</a>
                {% endfor %}
            </div>
        </nav>
    </header>

    <main>
        {{ content }}
    </main>

    <footer>
        <p>&copy; {{ site.time | date: '%Y' }} {{ site.title }}. All rights reserved.</p>
    </footer>
</body>
</html>

# File: _layouts/post.html
---
layout: default
---
<article class="post">
    <header class="post-header">
        <h1>{{ page.title }}</h1>
        <p class="post-meta">
            {{ page.date | date: site.date_format }} {% if page.author %}• {{ page.author }}{% endif %}
        </p>
    </header>

    <div class="post-content">
        {{ content }}
    </div>
</article>

# File: _layouts/project.html
---
layout: default
---
<article class="project">
    <header class="project-header">
        <h1>{{ page.title }}</h1>
        {% if page.github_link %}
        <a href="{{ page.github_link }}" class="github-link">View on GitHub</a>
        {% endif %}
    </header>

    <div class="project-content">
        {{ content }}
    </div>
</article>

# File: assets/css/style.scss
---
---
@import "minima";

// Custom styles
:root {
    --primary-color: #2c3e50;
    --secondary-color: #3498db;
    --background-color: #ffffff;
    --text-color: #333333;
    --link-color: #3498db;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: var(--text-color);
    background-color: var(--background-color);
}

.site-title {
    font-size: 1.5rem;
    font-weight: bold;
    color: var(--primary-color);
    text-decoration: none;
}

nav {
    padding: 1rem;
    background-color: var(--background-color);
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.nav-links {
    display: flex;
    gap: 1rem;
    
    a {
        color: var(--primary-color);
        text-decoration: none;
        
        &:hover {
            color: var(--secondary-color);
        }
    }
}

main {
    max-width: 800px;
    margin: 2rem auto;
    padding: 0 1rem;
}

.post, .project {
    margin-bottom: 3rem;
    
    h1 {
        color: var(--primary-color);
    }
}

.post-meta {
    color: #666;
    font-size: 0.9rem;
}

footer {
    text-align: center;
    padding: 2rem;
    background-color: var(--primary-color);
    color: white;
}

# File: index.md
---
layout: default
title: Home
---

# Welcome

Hello! I'm James Baierski, a professional focused on building great digital experiences. This site showcases my work and thoughts on technology, design, and development.

## Recent Posts

{% for post in site.posts limit:3 %}
* [{{ post.title }}]({{ post.url | relative_url }})
  {{ post.excerpt }}
{% endfor %}

## Featured Projects

{% for project in site.projects limit:2 %}
* [{{ project.title }}]({{ project.url | relative_url }})
  {{ project.excerpt }}
{% endfor %}

# File: about.md
---
layout: page
title: About
permalink: /about/
---

# About Me

I'm a passionate professional with expertise in technology and development. I believe in creating meaningful digital experiences that make a difference.

## Experience

- Current Role: [Your Current Role]
- Previous Experience: [Brief Overview]
- Skills: [Key Skills]

## Education

- [Degree] from [University]
- [Relevant Certifications]

# File: contact.md
---
layout: page
title: Contact
permalink: /contact/
---

# Get in Touch

I'm always interested in new opportunities and collaborations. Feel free to reach out through any of the following channels:

- Email: [Your Email]
- LinkedIn: [LinkedIn Profile]
- GitHub: [GitHub Profile]

# File: _posts/2024-12-28-welcome-post.md
---
layout: post
title: "Welcome to My New Site"
date: 2024-12-28
categories: [announcements]
---

Welcome to my new website! This space will serve as a platform for sharing my thoughts on technology, development, and various projects I'm working on. Stay tuned for more content!

# File: _projects/project1.md
---
layout: project
title: "Project One"
github_link: "https://github.com/username/project-one"
---

Description of your first project. Include key features, technologies used, and outcomes achieved.

# File: .gitignore
_site
.sass-cache
.jekyll-cache
.jekyll-metadata
vendor
.DS_Store
