title: James Baierski
#logo:
theme: jekyll-theme-minimal
permalink: /:title/
excerpt_separator: '\n\n\n'
date_format: '%B %d , %Y'
kramdown:
  input: Kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/jbaierski


