# _config.yml
title: James Baierski
description: Professional Portfolio
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - Excel.md
  - Misc.md
  - Modules.md
  - Projects.md
  - Python.md
  - SQL.md
  - Skills.md

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# File: _layouts/default.html
---
layout: default
---
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page.title }} | {{ site.title }}</title>
    <link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">
</head>
<body>
    <header>
        <nav>
            <a href="{{ '/' | relative_url }}" class="site-title">{{ site.title }}</a>
            <div class="nav-links">
                {% for item in site.header_pages %}
                    <a href="{{ item.url | relative_url }}">{{ item.title }}</a>
                {% endfor %}
            </div>
        </nav>
    </header>

    <main>
        {{ content }}
    </main>

    <footer>
        <p>&copy; {{ site.time | date: '%Y' }} {{ site.title }}</p>
    </footer>
</body>
</html>

# File: assets/css/style.scss
---
---
@import "minima";

:root {
    --primary-color: #2c3e50;
    --secondary-color: #3498db;
    --background-color: #ffffff;
    --text-color: #333333;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    line-height: 1.6;
    color: var(--text-color);
    background-color: var(--background-color);
}

nav {
    padding: 1rem;
    background-color: var(--background-color);
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    
    .site-title {
        font-size: 1.5rem;
        font-weight: bold;
        color: var(--primary-color);
        text-decoration: none;
    }
    
    .nav-links {
        display: flex;
        gap: 1rem;
        
        a {
            color: var(--primary-color);
            text-decoration: none;
            
            &:hover {
                color: var(--secondary-color);
            }
        }
    }
}

main {
    max-width: 800px;
    margin: 2rem auto;
    padding: 0 1rem;
}

# File: index.md
---
layout: default
title: Home
---

# Welcome

Welcome to my professional portfolio. Here you'll find my expertise across various technical domains including Excel, Python, SQL, and more.

# File: Excel.md
---
layout: page
title: Excel
permalink: /excel/
---

## Excel Expertise

### Advanced Functions
- Complex formulas and calculations
- VLOOKUP, INDEX-MATCH, and array formulas
- Pivot Tables and data analysis

### Automation
- VBA Macros
- Excel automation scripts
- Custom worksheet functions

### Data Analysis
- Data cleaning and validation
- Statistical analysis
- Financial modeling

# File: Misc.md
---
layout: page
title: Miscellaneous
permalink: /misc/
---

## Additional Skills & Tools

### Version Control
- Git fundamentals
- Repository management
- Collaboration workflows

### Project Management
- Agile methodologies
- Task tracking
- Team coordination

### Documentation
- Technical writing
- API documentation
- Process documentation

# File: Modules.md
---
layout: page
title: Modules
permalink: /modules/
---

## Software Modules

### Custom Components
- Reusable code libraries
- Plugin development
- API integrations

### Architecture
- Modular design patterns
- Component lifecycle
- Integration strategies

### Documentation
- Module specifications
- Usage guidelines
- API references

# File: Projects.md
---
layout: page
title: Projects
permalink: /projects/
---

## Project Portfolio

### Featured Projects
[Project details and descriptions will go here]

### Technical Implementations
- Project scope and objectives
- Technologies used
- Outcomes and results

### Case Studies
- Problem-solving approaches
- Implementation details
- Success metrics

# File: Python.md
---
layout: page
title: Python
permalink: /python/
---

## Python Development

### Core Skills
- Object-oriented programming
- Data structures and algorithms
- Error handling and debugging

### Frameworks & Libraries
- Web frameworks (Django, Flask)
- Data analysis (Pandas, NumPy)
- Machine learning (Scikit-learn)

### Development Tools
- Virtual environments
- Package management
- Testing frameworks

# File: SQL.md
---
layout: page
title: SQL
permalink: /sql/
---

## SQL & Database Management

### Query Development
- Complex SQL queries
- Stored procedures
- Performance optimization

### Database Design
- Schema design
- Normalization
- Index optimization

### Administration
- Database maintenance
- Backup and recovery
- Security management

# File: Skills.md
---
layout: page
title: Skills
permalink: /skills/
---

## Technical Proficiencies

### Programming Languages
- Python
- SQL
- VBA

### Data Analysis
- Excel advanced functions
- Statistical analysis
- Data visualization

### Tools & Technologies
- Version control (Git)
- Database management
- Project management tools

# File: .gitignore
_site
.sass-cache
.jekyll-cache
.jekyll-metadata
vendor
.DS_Store
