# Site settings
title: Your Site Name
email: your-email@example.com
description: >- # this means ignore newlines until next key
  Write your site description here. This will appear in search engine results
  and social media previews.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com
github_username: your-username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

