# _config.yml
title: James Baierski
description: Professional Portfolio
baseurl: ""
url: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - Excel.md
  - Misc.md
  - Modules.md
  - Projects.md
  - Python.md
  - SQL.md
  - Skills.md

